name: Run web scraper

on: [workflow_dispatch]

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
              python-version: '3.13'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Install Playwright browsers
          run: playwright install

        - name: Run web scraper
          env: 
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASS: ${{ secrets.DB_PASS }}
            DB_SSL: ${{ secrets.DB_SSL }}
            SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}
            
          run: |
              cd scrappingtickets
              scrapy crawl ticketspider

        - name: Commit and push changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
              commit_message: Update ticket data
          id: auto-commit-action

        - name: Send Email
          if: steps.auto-commit-action.outputs.committed == 'true'
          uses: dawidd6/action-send-mail@v3
          with:
              server_address: smtp.gmail.com
              server_port: 465
              username: ${{ secrets.EMAIL_USERNAME }}
              password: ${{ secrets.EMAIL_PASSWORD }}
              subject: Ticket Data Updated
              body: |
                The ticket data has been successfully updated and committed to the repository.

                ${{ steps.auto-commit-action.outputs.committed }}
              to: soph.bor06@gmail.com
              from: Scrappy Web Server
              attachments: data/ticketdata.json
                